//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSWeb.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoanManagementSystemEntities : DbContext
    {
        public LoanManagementSystemEntities()
            : base("name=LoanManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<tbl_Address> tbl_Address { get; set; }
        public virtual DbSet<tbl_Customer> tbl_Customer { get; set; }
        public virtual DbSet<tbl_LMSUser> tbl_LMSUser { get; set; }
        public virtual DbSet<tbl_Loan> tbl_Loan { get; set; }
        public virtual DbSet<tbl_LoanPayments> tbl_LoanPayments { get; set; }
        public virtual DbSet<tbl_LoanTypes> tbl_LoanTypes { get; set; }
        public virtual DbSet<tbl_MaritalStatus> tbl_MaritalStatus { get; set; }
        public virtual DbSet<tbl_Session> tbl_Session { get; set; }
    }
}
