//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Customer()
        {
            this.tbl_Loan = new HashSet<tbl_Loan>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string AdhaarNo { get; set; }
        public string MobileNo { get; set; }
        public string PANCard { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public Nullable<decimal> AnnualIncome { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> PresentAddressId { get; set; }
        public Nullable<int> PermanentAddressId { get; set; }
    
        public virtual tbl_Address tbl_Address { get; set; }
        public virtual tbl_Address PresentAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Loan> tbl_Loan { get; set; }
        public virtual tbl_MaritalStatus tbl_MaritalStatus { get; set; }
    }
}
