//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Loan()
        {
            this.tbl_LoanPayments = new HashSet<tbl_LoanPayments>();
        }
    
        public int Id { get; set; }
        public string LoanNo { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string LoanStatus { get; set; }
        public Nullable<int> LoanTypeId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<double> interestrate { get; set; }
        public Nullable<int> NoOfInstallaments { get; set; }
        public Nullable<int> PaidInstallaments { get; set; }
        public string Nominee { get; set; }
        public Nullable<int> NomineeAddressID { get; set; }
        public string NomineeRelationShip { get; set; }
    
        public virtual tbl_Address tbl_Address { get; set; }
        public virtual tbl_Customer tbl_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LoanPayments> tbl_LoanPayments { get; set; }
        public virtual tbl_LoanTypes tbl_LoanTypes { get; set; }
    }
}
